#! /bin/sh

sxhkd &
feh --bg-scale ~/pic/20.jpg &
bspc monitor -d I II III IV V VI VII VIII IX X
tint2 &
bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          1.25
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config click_to_focus true
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config active_border_color  "${color['bt_blue']}"
bspc config focused_border_color "${color['bt_green']}"
